# Config File
output_folder: "experiments"
experiment_name: "db4_no_electronics"

workers: 8
img_size: 544
ignore_classes:
  - 4
  - 6

model:
  anchors:
    - [10, 13]
    - [16, 30]
    - [33, 23]
    - [30, 61]
    - [62, 45]
    - [59, 119]
    - [116, 90]
    - [156, 198]
    - [373, 326]

train:
  dir: '/home/brian/Documents/datasets/new_smith_full/images'
  annotation_file: '/home/brian/Documents/datasets/new_smith_full/random_train_fixed_coco.json'
  val_dir: ~
  val_annotation_file: ~
  val_split: 0.2
  normalized: false
  output_name: "yolov3_xray_544.pt"

  epochs: 100
  gradient_accumulations: 1
  batch_size: 6
  pretrained_weights: "pretrained_weights/yolov3-openimages.weights"
  checkpoint_interval: 5
  evaluation_interval: 1
  augment: false
  compute_map: false  # if True computes mAP every tenth batch
  multiscale_training: true # allow for multi-scale training
  iou_thres: 0.5
  nms_thres: 0.5
  conf_thres: 0.5

  optimizer:
    # Possible values for type: "adam, sgd"
    type: "adam"
    lr: 0.0001
    momentum: 0.9  # Only for SGD
    decay: 0.0005
    scheduler_milestones:
      - 30
      - 40
    gamma: 0.1

test:
  weights_file: PATH TO WEIGHTS FILE
  dir: IMAGES DIR
  annotation_file: ANNOTATIONS FILE
  batch_size: 8
  normalized: false
  iou_thres: 0.5
  nms_thres: 0.4
  conf_thres: 0.8
  json_file_output: OUTPUT FILE

inference:
  weights_file: PATH TO WEIGHTS FILE
  dir: IMAGES DIR
  annotation_file: ANNOTATIONS FILE (OPTIONAL)
  normalized: false
  with_gt: true
  batch_size: 16
  max_images: -1 # Number of maximum images to infer. If -1, infers all from inference directory
  classes:
    - firearm
    - firearmparts
    - knife
    - ceramic knife
  nms_thres: 0.4
  conf_thres: 0.8
  save_structured: true

visdom:
  show: true
  host: 'localhost'
  port: 8097
